linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - revive
    - ineffassign
    - vet
    - unused
    - misspell
    - bodyclose
    - errcheck
    - goimports
    - prealloc

issues:
  exclude-dirs:
    - vendor
run:
  deadline: 2m
  skip-dirs:
    - vendor
