linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - revive
    - ineffassign
    - unused
    - misspell
    - bodyclose
    - errcheck
    - goimports
    - prealloc

run:
  deadline: 2m

issues:
  skip-dirs:
    - vendor
    - ui
