name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  gobot:
    name: Run gobot CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        go:
          - '1.21'
          - '1.22'

    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v4

    # copy-pasta from https://github.com/caddyserver/caddy/blob/master/.github/workflows/ci.yml
    - name: Print Go version and environment
      id: vars
      run: |
        printf "Using go at: $(which go)\n"
        printf "Go version: $(go version)\n"
        printf "\n\nGo environment:\n\n"
        go env
        printf "\n\nSystem environment:\n\n"
        env
        echo "::set-output name=go_cache::$(go env GOCACHE)"

    - name: Cache the build cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.vars.outputs.go_cache }}
        key: ${{ runner.os }}-${{ matrix.go }}-go-ci-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.go }}-go-ci

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  lint:
    name: Run golangci linter
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        go:
          - '1.21'
          - '1.22'

    steps:

    - name: Check out source code
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.56

  rustbot:
    name: Run rustbot CI
    runs-on: ubuntu-latest
    env:
      CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

    steps:
      - name: Update apt
        run: sudo apt update
      - name: Install alsa
        run: sudo apt install -y --no-install-recommends libasound2-dev pkg-config

      - name: check out code
        uses: actions/checkout@v4

      - name: cargo version and environment
        id: vars
        run: |
          printf "Using cargo at: $(which cargo)\n"
          printf "cargo version: $(cargo version)\n"

      - name: setup rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: run build
        run: |
          cargo check --manifest-path rustbot/Cargo.toml --verbose
          cargo build --manifest-path rustbot/Cargo.toml --release --verbose

      - name: run tests
        run: cargo test --manifest-path rustbot/Cargo.toml --verbose
